### ISSUE TITLE
PR #28 Section 3.1 University ERD

### ISSUE THREAD

**Issue by davaya** [oasis-tcs/openc2-jadn-im#32]
For all entity relationship diagrams (GraphViz and PlantUML), all node content should be in JIDL format.  The UnivId simple type in the green oval should be 
```
UnivId = String{pattern="^U-\d{6}$"}
```
rather than showing the % option.  The JADN type option string is `"%^U-\\d{6}$"`

**Comment by dlemire60** [comment]
This diagram and its GraphViz source are corrected in the CN02 version (Nov/Dec 2024).  Closing this issue.
