### ISSUE TITLE
README typos

### ISSUE THREAD

**Issue by davaya** [oasis-tcs/openc2-jadn-im#5]
In the last paragraph, the template includes \<tc short name\>, which markdown treats as an HTML "tc" element instead of a field to be replaced by the editor.  Replace it with "OpenC2".  Suggest to OASIS admin that replaceable  fields use some other syntax that stands out to editors and won't be invisibly eaten by markdown, like &tc short name&.

The cute icons on each of the headings confuse the "Contributions" and "Licensing" links in the first paragraph.

**Comment by dlemire60** [comment]
Good catches. 

Fixed in the JADN-IM published and working branches, respectively by PRs #6 and #7.

I'll also update the template in TC-Ops.

And the icons aren't cute, they're helpful!  :-)
